package com.tripfactory.nomad.service.impl;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.format.DateTimeFormatter;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Component;

import com.tripfactory.nomad.domain.entity.Payment;
import com.tripfactory.nomad.domain.entity.TripRequest;

/**
 * Builds a simple one-page PDF payment receipt using Apache PDFBox
 * (Apache 2.0 licensed - free, no license fees, no usage limits).
 */
@Component
public class ReceiptPdfGenerator {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm");

    public byte[] generate(Payment payment, TripRequest tripRequest) {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            try (PDPageContentStream stream = new PDPageContentStream(document, page)) {
                float margin = 60;
                float y = page.getMediaBox().getHeight() - margin;
                float width = page.getMediaBox().getWidth() - 2 * margin;

                PDType1Font titleFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                PDType1Font bodyFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

                y = writeLine(stream, titleFont, 22, margin, y, "NOMAD - Payment Receipt");
                y -= 20;
                y = writeLine(stream, bodyFont, 11, margin, y, "Receipt generated: " + java.time.LocalDateTime.now().format(DATE_FORMAT));
                y -= 25;

                y = writeLine(stream, titleFont, 13, margin, y, "Trip Details");
                y -= 5;
                y = drawDivider(stream, margin, y, width);
                y = writeLine(stream, bodyFont, 11, margin, y, "Trip ID: #" + tripRequest.getId());
                y = writeLine(stream, bodyFont, 11, margin, y, "Destination: " + nullSafe(tripRequest.getCity()));
                y = writeLine(stream, bodyFont, 11, margin, y, "Status: " + tripRequest.getStatus());
                y -= 15;

                y = writeLine(stream, titleFont, 13, margin, y, "Payment Details");
                y -= 5;
                y = drawDivider(stream, margin, y, width);
                y = writeLine(stream, bodyFont, 11, margin, y, "Payment ID: " + nullSafe(payment.getRazorpayPaymentId()));
                y = writeLine(stream, bodyFont, 11, margin, y, "Order ID: " + nullSafe(payment.getRazorpayOrderId()));
                y = writeLine(stream, bodyFont, 11, margin, y, "Amount Paid: Rs. " + payment.getAmount());
                y = writeLine(stream, bodyFont, 11, margin, y, "Status: " + payment.getPaymentStatus());
                y -= 15;

                y = writeLine(stream, titleFont, 13, margin, y, "Customer");
                y -= 5;
                y = drawDivider(stream, margin, y, width);
                y = writeLine(stream, bodyFont, 11, margin, y, "Name: " + nullSafe(tripRequest.getUser().getName()));
                y = writeLine(stream, bodyFont, 11, margin, y, "Email: " + nullSafe(tripRequest.getUser().getEmail()));
                y -= 30;

                writeLine(stream, bodyFont, 9, margin, y, "This is a test-mode receipt generated by NOMAD - Smart Weekend Travel & Assistance.");
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            document.save(out);
            return out.toByteArray();
        } catch (IOException ex) {
            throw new RuntimeException("Failed to generate receipt PDF", ex);
        }
    }

    private float writeLine(PDPageContentStream stream, PDType1Font font, float size, float x, float y, String text)
            throws IOException {
        stream.beginText();
        stream.setFont(font, size);
        stream.newLineAtOffset(x, y);
        stream.showText(text);
        stream.endText();
        return y - (size + 8);
    }

    private float drawDivider(PDPageContentStream stream, float x, float y, float width) throws IOException {
        stream.setLineWidth(0.5f);
        stream.moveTo(x, y);
        stream.lineTo(x + width, y);
        stream.stroke();
        return y - 15;
    }

    private String nullSafe(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}
